import type { Product } from "@/types/product";

// prettier-ignore
export const PRODUCTS: Product[] = [
  { id: 1, name: "Khamrah", brand: "Lattafa", price: 18500, size: "100ml", gender: "Unisex", type: "Sweet", rating: 4.9, reviewCount: 124, badge: "Best Seller", isNew: false, notes: { top: "Cinnamon, Cardamom", heart: "Rose, Jasmine", base: "Oud, Amber, Musk" }, longevity: "10–12h", projection: "Strong", season: "Autumn/Winter", occasion: "Evening", longevityPct: 90, projectionPct: 85 },
  { id: 2, name: "Oud Mood", brand: "Lattafa", price: 22000, size: "100ml", gender: "Men", type: "Woody", rating: 4.8, reviewCount: 87, isNew: false, notes: { top: "Bergamot, Saffron", heart: "Oud, Rose", base: "Sandalwood, Amber" }, longevity: "12+ h", projection: "Very Strong", season: "All Year", occasion: "Special", longevityPct: 95, projectionPct: 90 },
  { id: 3, name: "Mayar", brand: "Hayati", price: 14500, size: "50ml", gender: "Women", type: "Fresh", rating: 4.7, reviewCount: 63, badge: "New", isNew: true, notes: { top: "Citrus, Peach", heart: "Freesia, Lily", base: "Musk, Cedarwood" }, longevity: "7–9h", projection: "Moderate", season: "Spring/Summer", occasion: "Daily", longevityPct: 70, projectionPct: 60 },
  { id: 4, name: "Supremacy Silver", brand: "Afnan", price: 16000, size: "100ml", gender: "Men", type: "Fresh", rating: 4.8, reviewCount: 95, isNew: false, notes: { top: "Lemon, Bergamot", heart: "Apple, Lavender", base: "Vetiver, Musk" }, longevity: "8–10h", projection: "Moderate", season: "Spring/Summer", occasion: "Daily", longevityPct: 75, projectionPct: 65 },
  { id: 5, name: "Bouquet Amirah", brand: "Ard Al Zaafaran", price: 12500, size: "50ml", gender: "Women", type: "Sweet", rating: 4.6, reviewCount: 52, isNew: true, notes: { top: "Peach, Apple", heart: "Rose, Jasmine", base: "Musk, Vanilla" }, longevity: "6–8h", projection: "Soft", season: "All Year", occasion: "Daily", longevityPct: 65, projectionPct: 50 },
  { id: 6, name: "Yara", brand: "Lattafa", price: 15500, size: "100ml", gender: "Women", type: "Oriental", rating: 4.9, reviewCount: 118, badge: "Best Seller", isNew: false, notes: { top: "Raspberry, Mandarin", heart: "Tuberose, Jasmine", base: "Vanilla, Musk" }, longevity: "10–12h", projection: "Strong", season: "Autumn/Winter", occasion: "Evening", longevityPct: 88, projectionPct: 80 },
  { id: 7, name: "Asateer Night", brand: "Lattafa", price: 19500, size: "100ml", gender: "Men", type: "Spicy", rating: 4.7, reviewCount: 41, badge: "New", isNew: true, notes: { top: "Saffron, Black Pepper", heart: "Oud, Patchouli", base: "Amber, Musk" }, longevity: "12+ h", projection: "Very Strong", season: "Winter", occasion: "Evening", longevityPct: 95, projectionPct: 92 },
  { id: 8, name: "Fakhar Gold", brand: "Lattafa", price: 25000, size: "100ml", gender: "Unisex", type: "Woody", rating: 4.8, reviewCount: 76, isNew: false, notes: { top: "Lemon, Cardamom", heart: "Oud, Rose", base: "Sandalwood, Amber" }, longevity: "12+ h", projection: "Strong", season: "All Year", occasion: "Special", longevityPct: 92, projectionPct: 86 },
  { id: 9, name: "9PM", brand: "Afnan", price: 13500, size: "100ml", gender: "Men", type: "Sweet", rating: 4.7, reviewCount: 88, isNew: false, notes: { top: "Bergamot, Apple", heart: "Cinnamon, Lavender", base: "Vanilla, Musk" }, longevity: "8–10h", projection: "Moderate", season: "Autumn/Winter", occasion: "Evening", longevityPct: 78, projectionPct: 72 },
  { id: 10, name: "Supremacy Pink", brand: "Afnan", price: 14000, size: "100ml", gender: "Women", type: "Fresh", rating: 4.6, reviewCount: 59, isNew: false, notes: { top: "Peach, Raspberry", heart: "Rose, Jasmine", base: "Musk, Cedarwood" }, longevity: "7–9h", projection: "Soft", season: "Spring", occasion: "Daily", longevityPct: 68, projectionPct: 55 },
  { id: 11, name: "Hayati Noir", brand: "Hayati", price: 21000, size: "100ml", gender: "Unisex", type: "Woody", rating: 4.8, reviewCount: 44, badge: "New", isNew: true, notes: { top: "Bergamot, Neroli", heart: "Oud, Amber", base: "Sandalwood, Musk" }, longevity: "12+ h", projection: "Strong", season: "Autumn/Winter", occasion: "Evening", longevityPct: 90, projectionPct: 82 },
  { id: 12, name: "Aseel", brand: "Ard Al Zaafaran", price: 11500, size: "50ml", gender: "Women", type: "Oriental", rating: 4.5, reviewCount: 37, isNew: false, notes: { top: "Rose, Jasmine", heart: "Oud, Sandalwood", base: "Amber, Musk" }, longevity: "8–10h", projection: "Moderate", season: "All Year", occasion: "Daily", longevityPct: 74, projectionPct: 62 },
  { id: 13, name: "Pride", brand: "Lattafa", price: 17500, size: "100ml", gender: "Men", type: "Spicy", rating: 4.7, reviewCount: 56, isNew: false, notes: { top: "Saffron, Cardamom", heart: "Oud, Leather", base: "Amber, Musk" }, longevity: "12+ h", projection: "Strong", season: "Winter", occasion: "Special", longevityPct: 88, projectionPct: 84 },
  { id: 14, name: "Warda", brand: "Hayati", price: 13000, size: "50ml", gender: "Women", type: "Sweet", rating: 4.6, reviewCount: 48, isNew: false, notes: { top: "Rose, Peach", heart: "Jasmine, Lily", base: "Musk, Vanilla" }, longevity: "7–9h", projection: "Soft", season: "Spring/Summer", occasion: "Daily", longevityPct: 68, projectionPct: 52 },
  { id: 15, name: "Oud Isphahan", brand: "Ard Al Zaafaran", price: 28000, size: "100ml", gender: "Unisex", type: "Woody", rating: 4.9, reviewCount: 92, badge: "Premium", isNew: false, notes: { top: "Saffron, Rose", heart: "Oud, Patchouli", base: "Sandalwood, Amber" }, longevity: "12+ h", projection: "Very Strong", season: "All Year", occasion: "Special", longevityPct: 96, projectionPct: 94 },
  { id: 16, name: "Maqbool Oud", brand: "Ard Al Zaafaran", price: 24000, size: "100ml", gender: "Men", type: "Woody", rating: 4.8, reviewCount: 65, isNew: false, notes: { top: "Bergamot, Lemon", heart: "Oud, Saffron", base: "Sandalwood, Musk" }, longevity: "12+ h", projection: "Strong", season: "Autumn/Winter", occasion: "Evening", longevityPct: 92, projectionPct: 88 },
  { id: 17, name: "Tender Hearts", brand: "Lattafa", price: 9500, size: "50ml", gender: "Women", type: "Fresh", rating: 4.5, reviewCount: 41, isNew: false, notes: { top: "Peach, Apricot", heart: "Rose, Jasmine", base: "Musk, White Cedar" }, longevity: "6–8h", projection: "Soft", season: "Spring", occasion: "Daily", longevityPct: 62, projectionPct: 48 },
  { id: 18, name: "Raghba", brand: "Lattafa", price: 11000, size: "100ml", gender: "Unisex", type: "Sweet", rating: 4.7, reviewCount: 103, badge: "Best Seller", isNew: false, notes: { top: "Cinnamon, Coffee", heart: "Rose, Oud", base: "Amber, Musk" }, longevity: "10–12h", projection: "Strong", season: "Autumn/Winter", occasion: "Evening", longevityPct: 86, projectionPct: 80 },
  { id: 19, name: "Niche Oud", brand: "Afnan", price: 32000, size: "100ml", gender: "Unisex", type: "Woody", rating: 4.9, reviewCount: 38, badge: "Premium", isNew: false, notes: { top: "Saffron, Bergamot", heart: "Oud, Rose", base: "Amber, Sandalwood" }, longevity: "12+ h", projection: "Very Strong", season: "All Year", occasion: "Special", longevityPct: 96, projectionPct: 93 },
  { id: 20, name: "Hayati Blanche", brand: "Hayati", price: 16500, size: "100ml", gender: "Women", type: "Fresh", rating: 4.7, reviewCount: 55, badge: "New", isNew: true, notes: { top: "Citrus, Bergamot", heart: "White Jasmine, Magnolia", base: "Musk, Cedarwood" }, longevity: "8–10h", projection: "Moderate", season: "Spring/Summer", occasion: "Daily", longevityPct: 74, projectionPct: 66 },
];
